openapi: 3.0.0
info:
  title: Recetas API
  version: 1.0.0
paths:
  /api/signup:
    post:
      summary: Registrarse
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/signUp'
            example:
              email: ejemplo@gmail.com
              password: "12345"
      responses:
        '201':
          description: Registro exitoso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Usuario ya existe
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: El usuario ya existe
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Error interno del servidor
components:
  requestBodies:
    signUp:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              email:
                type: string
                description: Email del usuario
              password:
                type: string
                description: Contraseña del usuario
            example:
              email: jorge@gmail.com
              password: "12345"
  schemas:
    User:
      type: object
      properties:
        id:
          type: number
        email:
          type: string
        password:
          type: string
        active:
          type: boolean
        createdAt:
          type: Date
        updatedAt:
          type: Date
        profile:
          type: object  # Deberías definir la estructura de Profile aquí
        photos:
          type: array   # Deberías definir la estructura de Photo aquí
      example:
        id: 1
        email: ejemplo@gmail.com
        password: "12345"
        active: true
        createdAt: '2023-02-02'
        updatedAt: '2023-02-02'
        profile: {}
        photos: []